
import type { Metadata } from "next";

import NavigationBar from "@/components/NavigationBar";

import { Mulish } from "next/font/google";
import "./globals.css";

import { Providers } from "@/components/Providers";


const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <NavigationBar/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
